apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  journal_entries: "10"
  redis_write_host: "redis-0.redis.default.svc.cluster.local"
  redis_read_host: "redis.default.svc.cluster.local"