apiVersion: v1
data:
  startup.sh: |-
    #!/bin/bash
    PASSWORD=$(cat /etc/redis-passwd/passwd)
    if [[ "${HOSTNAME}" == "redis-0" ]]; then
        redis-server --requirepass ${PASSWORD}
    else
        redis-server --replicaof redis-0.redis 6379 --masterauth ${PASSWORD} --requirepass ${PASSWORD}
    fi
kind: ConfigMap
metadata:
  name: redis-startup
